export const cards = [
  {
    id: 1,
    name: "Basic",
    price: 19.99,
    storage: "500 GB Storage",
    numberUsers: "2 Users Allowed",
    sendUp: "Send up to 3 GB",
    styleCardName: "card-white",
    cardContentTop: "card-white-content-top",
    cardContent: "card-white-content",
    cardContentDollar: "card-white-content-dollar",
  },
  {
    id: 2,
    name: "Professional",
    price: 24.99,
    storage: "1 TB Storage",
    numberUsers: "5 Users Allowed",
    sendUp: "Send up to 10 GB",
    styleCardName: "card-purple",
    cardContentTop: "card-purple-content-top",
    cardContent: "card-purple-content",
    cardContentDollar: "card-purple-content-dollar",
  },
  {
    id: 3,
    name: "Master",
    price: 39.99,
    storage: "2 TB Storage",
    numberUsers: "10 Users Allowed",
    sendUp: "Send up to 20 GB",
    styleCardName: "card-white",
    cardContentTop: "card-white-content-top",
    cardContent: "card-white-content",
    cardContentDollar: "card-white-content-dollar",
  },
];
